name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # todos os dias à meia-noite UTC
  workflow_dispatch:     # permite rodar manualmente
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Frausino
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      - name: Commit files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "generate github-contribution-grid-snake.svg"
          add: "dist/*.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to output branch
        run: |
          git fetch origin
          git checkout -B output
          git add dist/*.svg
          git commit -m "update snake"
          git push origin output --force
